// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatermark(arg1) {
  return window['go']['main']['App']['AddWatermark'](arg1);
}

export function AddWatermarkBatch(arg1) {
  return window['go']['main']['App']['AddWatermarkBatch'](arg1);
}

export function Adjust(arg1) {
  return window['go']['main']['App']['Adjust'](arg1);
}

export function AdjustBatch(arg1) {
  return window['go']['main']['App']['AdjustBatch'](arg1);
}

export function ApplyFilter(arg1) {
  return window['go']['main']['App']['ApplyFilter'](arg1);
}

export function ApplyFilterBatch(arg1) {
  return window['go']['main']['App']['ApplyFilterBatch'](arg1);
}

export function Compress(arg1) {
  return window['go']['main']['App']['Compress'](arg1);
}

export function CompressBatch(arg1) {
  return window['go']['main']['App']['CompressBatch'](arg1);
}

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function ConvertBatch(arg1) {
  return window['go']['main']['App']['ConvertBatch'](arg1);
}

export function EditMetadata(arg1) {
  return window['go']['main']['App']['EditMetadata'](arg1);
}

export function ExpandDroppedPaths(arg1) {
  return window['go']['main']['App']['ExpandDroppedPaths'](arg1);
}

export function GeneratePDF(arg1) {
  return window['go']['main']['App']['GeneratePDF'](arg1);
}

export function GetImagePreview(arg1) {
  return window['go']['main']['App']['GetImagePreview'](arg1);
}

export function GetInfo(arg1) {
  return window['go']['main']['App']['GetInfo'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SplitGIF(arg1) {
  return window['go']['main']['App']['SplitGIF'](arg1);
}

export function StripMetadata(arg1) {
  return window['go']['main']['App']['StripMetadata'](arg1);
}
