// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddWatermark(arg1:models.WatermarkRequest):Promise<models.WatermarkResult>;

export function AddWatermarkBatch(arg1:Array<models.WatermarkRequest>):Promise<Array<models.WatermarkResult>>;

export function Adjust(arg1:models.AdjustRequest):Promise<models.AdjustResult>;

export function AdjustBatch(arg1:Array<models.AdjustRequest>):Promise<Array<models.AdjustResult>>;

export function ApplyFilter(arg1:models.FilterRequest):Promise<models.FilterResult>;

export function ApplyFilterBatch(arg1:Array<models.FilterRequest>):Promise<Array<models.FilterResult>>;

export function Compress(arg1:models.CompressRequest):Promise<models.CompressResult>;

export function CompressBatch(arg1:Array<models.CompressRequest>):Promise<Array<models.CompressResult>>;

export function Convert(arg1:models.ConvertRequest):Promise<models.ConvertResult>;

export function ConvertBatch(arg1:Array<models.ConvertRequest>):Promise<Array<models.ConvertResult>>;

export function ExpandDroppedPaths(arg1:Array<string>):Promise<models.ExpandDroppedPathsResult>;

export function GeneratePDF(arg1:models.PDFRequest):Promise<models.PDFResult>;

export function GetInfo(arg1:models.InfoRequest):Promise<models.InfoResult>;

export function GetSettings():Promise<models.AppSettings>;

export function Ping():Promise<string>;

export function SaveSettings(arg1:models.AppSettings):Promise<models.AppSettings>;

export function SelectOutputDirectory():Promise<string>;

export function SplitGIF(arg1:models.GIFSplitRequest):Promise<models.GIFSplitResult>;
